@startuml
skinparam shadowing false
skinparam monochrome true
skinparam classAttributeIconSize 0
skinparam defaultFontName Arial

class ScriptableObject {
}

class CardData {
    + string cardName
    + string description
    + Sprite icon
    + int energyCost
    + CardType cardType
    + ElementType elementType
    + PlayTarget playTarget
}

class ChampionData {
    + int baseMaxHP
    + int baseSpeed
    + int basePhysicalDamage
}

class EnemyData {
    + int maxHP
    + int baseSpeed
    + int basePhysicalDamage
    + IntentData[] intents
}

class SkillData {
    + SkillType skillType
    + int baseDamage
    + int baseHeal
    + int baseArmor
}

class RelicData {
    + string relicName
    + string description
    + int cycleSpeed
    + SkillData[] possibleSkills
}

class TrinketData {
    + string trinketName
    + string description
    + int hpBonus
    + int speedBonus
}

ScriptableObject <|-- CardData
ScriptableObject <|-- RelicData
ScriptableObject <|-- TrinketData

CardData <|-- ChampionData
CardData <|-- EnemyData
CardData <|-- SkillData

@enduml
